syntax = "proto3";

package booking;

service BookingService {
  rpc CreateBooking (CreateBookingRequest) returns (BookingResponse);
  rpc GetBooking (GetBookingRequest) returns (BookingResponse);
  rpc GetBookings (GetBookingsRequest) returns (BookingListResponse);
  rpc UpdateBookingStatus (UpdateBookingStatusRequest) returns (BookingResponse);
  rpc AcceptBooking (GetBookingRequest) returns (BookingResponse);
  rpc CancelBooking (CancelBookingRequest) returns (BookingResponse);
  rpc RejectBooking (GetBookingRequest) returns (BookingResponse);
}

message CreateBookingRequest {
  int32 customer_id = 1;
  double pickup_latitude = 2;
  double pickup_longitude = 3;
  double destination_latitude = 4;
  double destination_longitude = 5;
  string vehicle_type = 6;
}

message GetBookingRequest {
  int32 id = 1;
}

message GetBookingsRequest {}

message UpdateBookingStatusRequest {
  int32 id = 1;
  string status = 2;
}

message CancelBookingRequest {
  int32 id = 1;
  string cancel_reason = 2;
}

message BookingResponse {
  int32 id = 1;
  int32 customer_id = 2;
  int32 driver_id = 3;
  double pickup_latitude = 4;
  double pickup_longitude = 5;
  double destination_latitude = 6;
  double destination_longitude = 7;
  string vehicle_type = 8;
  string status = 9;
  string cancel_reason = 10;
}

message BookingListResponse {
  repeated BookingResponse bookings = 1;
}
